version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  service:
    container_name: service
    command: "./service"
    build: .
    restart: always
    depends_on:
      - postgres
    expose:
      - ${APISERVER_PORT}
    ports:
      - ${APISERVER_PORT}:${APISERVER_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      APISERVER_PORT: ${APISERVER_PORT}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
volumes:
  db-data: