create table users(
    id int generated by default as identity primary key,
    username text unique not null,
    password text not null
);

create table merchandise(
    id int generated by default as identity primary key,
    name text unique not null,
    price int not null
);

create table balances(
    user_id int not null,
    balance int default 1000,
    foreign key (user_id) references users (id) on delete cascade
);

create table transactions(
    id int generated by default as identity primary key,
    user_id_from int not null,
    user_id_to int not null,
    amount int not null,
    created_at timestamp without time zone default NOW(),
    foreign key (user_id_from) references users(id) on delete cascade,
    foreign key (user_id_to) references users(id) on delete cascade
--  добавила created at, про него в задании не было сказано
);

create table purchases(
    id int generated by default as identity primary key,
    user_id int not null,
    merchandise_id int not null,
    created_at timestamp without time zone default NOW(),
    foreign key (user_id) references users(id) on delete cascade,
    foreign key (merchandise_id) references merchandise(id) on delete cascade
);

insert into merchandise
    (name, price)
values
    ('t-shirt', 80),
    ('cup', 20),
    ('book', 50),
    ('pen', 10),
    ('powerbank', 200),
    ('hoody', 300),
    ('umbrella', 200),
    ('socks',	10),
    ('wallet', 50),
    ('pink-hoody', 500);

-- psql -U tinepple -d trainee_task
